# Generated by Django 2.2.3 on 2019-07-15 19:02

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(default=None, upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=None, verbose_name='Active')),
                ('user_type', models.CharField(choices=[('developer', 'Developer'), ('lender', 'Lender'), ('banker', 'Banker')], default=None, max_length=20, verbose_name='Sign up as')),
                ('f_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('l_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('company_name', models.CharField(max_length=100, verbose_name='Name of Company')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number')),
                ('activated_on', models.DateTimeField(blank=True, null=True, verbose_name='Activated on()')),
                ('expire_time', models.DateTimeField(blank=True, null=True, verbose_name='Expire On')),
            ],
        ),
        migrations.CreateModel(
            name='WaterMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_mark_image', models.ImageField(default=None, upload_to='water_mark')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialUserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userlog_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Logged in at (Datetime): ')),
                ('userlog_date', models.DateField(blank=True, null=True, verbose_name='Logged in at: (Date)')),
                ('userlog_time', models.TimeField(blank=True, null=True, verbose_name='Logged in at (Time): ')),
                ('specialuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SpecialUser')),
            ],
        ),
    ]
