# Generated by Django 2.1 on 2019-10-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specuser',
            name='user_type',
            field=models.CharField(choices=[('developer', 'Developer'), ('lender', 'Lender'), ('banker', 'Banker'), ('dealer', 'Dealer'), ('homeowner', 'Prospective Homeowner'), ('Municipality/Government Official', 'Municipality/Government Official'), ('vendor', 'Vendor')], default=None, max_length=32, verbose_name='Sign up as'),
        ),
    ]
