# Generated by Django 2.2.3 on 2020-01-25 12:35

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Optional', max_length=18, null=True, region=None, verbose_name='Phone Number'),
        ),
    ]
