# Generated by Django 2.2.3 on 2019-07-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='watermarked_image',
            field=models.ImageField(default=None, upload_to='wartermark_photos'),
        ),
    ]
