# Generated by Django 2.2.3 on 2019-09-05 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialuserlog',
            name='specialuser',
        ),
        migrations.DeleteModel(
            name='Dealer',
        ),
        migrations.DeleteModel(
            name='SpecialUser',
        ),
        migrations.DeleteModel(
            name='SpecialUserLog',
        ),
    ]
