# Generated by Django 2.2.3 on 2019-08-14 10:05

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='dealer_no',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$')], verbose_name='Dealer Number'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone Number'),
        ),
    ]
