# Generated by Django 2.2.3 on 2019-07-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_photo_watermarked_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='watermarked_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='wartermarked_photos'),
        ),
        migrations.AlterField(
            model_name='watermark',
            name='water_mark_image',
            field=models.ImageField(default=None, help_text='You can add atmost one WaterMark image', upload_to='water_mark'),
        ),
    ]
