# Generated by Django 2.2.3 on 2019-08-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190814_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='content_page_link',
            field=models.URLField(blank=True, null=True, verbose_name='Structural Conttent Page link'),
        ),
    ]
