# Generated by Django 2.2.3 on 2020-06-02 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200220_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillist',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='specuser',
            name='dealer_no',
            field=models.CharField(blank=True, help_text='optional', max_length=6, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$')], verbose_name='Dealer Number'),
        ),
        migrations.AlterField(
            model_name='specuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='optional', max_length=18, null=True, verbose_name='Phone Number'),
        ),
    ]
