# Generated by Django 2.2.3 on 2020-06-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200602_1548'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='WaterMark',
        ),
        migrations.RemoveField(
            model_name='emaillist',
            name='name',
        ),
        migrations.AddField(
            model_name='specuser',
            name='address',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='specuser',
            name='city',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='specuser',
            name='country',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='specuser',
            name='postal',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Postal'),
        ),
        migrations.AddField(
            model_name='specuser',
            name='state',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='State'),
        ),
    ]
