# Generated by Django 2.1 on 2020-01-31 18:44

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userpreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='learn_about_electric_drive',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=100, verbose_name='Do you wish to learn more about an optional electric-drive community transport vehicle?'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='other_type_of_development',
            field=models.CharField(max_length=300, verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='type_of_development',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('select all', 'Select All'), ('Commercial', 'Commercial'), ('Mixed-use', 'Mixed-use'), ('Multi-tenant', 'Multi-tenant'), ('Condominium', 'Condominium'), ('Townhome', 'Townhome'), ('Man Camp', 'Man Camp'), ('Mobile Home Park', 'Mobile Home Park'), ('RV Park', 'RV Park'), ('Park Home (as defined by Housing and Urban Development)', 'Park Home (as defined by Housing and Urban Development)'), ('Other', 'Other')], max_length=300, verbose_name='What type of development(s) are you seeking?'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='type_of_electric_vehicle_function',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Standard', 'Standard'), ('Capability to Load Handicapped Person Without Human Assistance', 'Capability to Load Handicapped Person Without Human Assistance')], max_length=300, verbose_name='An electric vehicle will be included with each housing unit. What type of electric vehicle function are you interested in?'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='type_of_smart_home',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Automated Home Shopping and Delivery', 'Automated Home Shopping and Delivery'), ('Self-Driving Transport to Local Shopping Centers', 'Self-Driving Transport to Local Shopping Centers'), ('Self-Driving Transport to Local Medical Facilities', 'Self-Driving Transport to Local Medical Facilities')], max_length=300, verbose_name='What type of smart home functionality are you interested in learning more about? '),
        ),
    ]
