# Generated by Django 2.2.3 on 2019-08-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_dealer_content_page_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialuser',
            name='user_type',
            field=models.CharField(choices=[('developer', 'Developer'), ('lender', 'Lender'), ('banker', 'Banker'), ('dealer', 'Dealer'), ('homeowner', 'Prospective Homeowner'), ('Municipality/Government Official', 'Municipality/Government Official')], default=None, max_length=32, verbose_name='Sign up as'),
        ),
    ]
