# Generated by Django 2.2.3 on 2020-06-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200605_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specuser',
            name='address',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Address'),
        ),
    ]
