# Generated by Django 2.1 on 2020-01-31 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200131_2344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpreferences',
            options={'verbose_name': 'UserPreference', 'verbose_name_plural': 'UserPreferences'},
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='user_obj',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.SpecUser'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='other_type_of_development',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Other'),
        ),
    ]
