# Generated by Django 2.2.3 on 2019-07-25 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190725_2352'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
