# Generated by Django 2.1 on 2020-02-05 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200201_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specuser',
            name='content_permission',
            field=models.BooleanField(default=False, verbose_name='Content Access'),
        ),
        migrations.AlterField(
            model_name='specuser',
            name='home_permission',
            field=models.BooleanField(default=False, verbose_name='Home Access'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='user_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SpecUser'),
        ),
    ]
