# Generated by Django 2.2.3 on 2020-06-18 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200605_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Model name')),
                ('beds', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Beds')),
                ('baths', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Baths')),
                ('sq_ft', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='SQ.ft')),
                ('parking_spaces', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Parking Spaces')),
                ('no_of_kitchen', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Number of Kitchen')),
                ('kitchen', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Kitchen')),
                ('bathroom', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Bathroom')),
                ('frame_material', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Frame Material')),
                ('price', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Price')),
                ('amenities', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Amenities')),
                ('floor', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='floor')),
                ('garage', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Garage')),
                ('fireplace', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Fireplace')),
                ('laundry', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Laundry')),
                ('interior_features', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Interior Features')),
                ('construction_material', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Construction Materials')),
            ],
        ),
        migrations.CreateModel(
            name='ModelImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, default='', max_length=900, null=True, verbose_name='Beds')),
                ('modelsinfo_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ModelsInfo')),
            ],
        ),
    ]
