# Generated by Django 2.2.3 on 2020-06-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_modelimages_modelsinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsinfo',
            name='model_dimension',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Model Dimensions'),
        ),
        migrations.AddField(
            model_name='modelsinfo',
            name='model_header',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Model Header'),
        ),
        migrations.AddField(
            model_name='modelsinfo',
            name='model_text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Text'),
        ),
    ]
