# Generated by Django 2.2.3 on 2020-06-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200619_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelimages',
            name='pdf_file_path',
            field=models.CharField(blank=True, default='', max_length=900, null=True, verbose_name='Beds'),
        ),
    ]
