# Generated by Django 2.2.3 on 2019-09-04 18:05

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190823_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.CharField(choices=[('developer', 'Developer'), ('lender', 'Lender'), ('banker', 'Banker'), ('dealer', 'Dealer'), ('homeowner', 'Prospective Homeowner'), ('Municipality/Government Official', 'Municipality/Government Official')], default=None, max_length=32, verbose_name='Sign up as')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of Company')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='XXX-XXX-XXXX', max_length=18, region=None, verbose_name='Phone Number')),
                ('dealer_no', models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$')], verbose_name='Dealer Number')),
                ('activation_time_home', models.DateTimeField(blank=True, null=True, verbose_name='Activation Time (Home)')),
                ('expire_time_home', models.DateTimeField(blank=True, null=True, verbose_name='Expire Time (Home)')),
                ('activation_time_spec_content', models.DateTimeField(blank=True, null=True, verbose_name='Activation Time (Content)')),
                ('expire_time_spec_content', models.DateTimeField(blank=True, null=True, verbose_name='Expire Time (Content)')),
            ],
            options={
                'verbose_name': 'Spec_User',
                'verbose_name_plural': 'Spec User',
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
