# Generated by Django 2.2.3 on 2019-07-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_emaillist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialuser',
            name='user_type',
            field=models.CharField(choices=[('developer', 'Developer'), ('lender', 'Lender'), ('banker', 'Banker'), ('dealer', 'Dealer'), ('homeowner', 'Prospective Homeowner')], default=None, max_length=20, verbose_name='Sign up as'),
        ),
    ]
