# Generated by Django 2.2.3 on 2019-09-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_specuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='specuser',
            name='content_permission',
            field=models.BooleanField(default=None, verbose_name='Content Access'),
        ),
        migrations.AddField(
            model_name='specuser',
            name='home_permission',
            field=models.BooleanField(default=None, verbose_name='Home Access'),
        ),
    ]
