# Generated by Django 2.2.3 on 2019-08-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190731_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialuser',
            name='dealer_no',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Dealer Number'),
        ),
    ]
