# Generated by Django 2.2.3 on 2019-08-03 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_specialuser_dealer_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialuser',
            name='dealer_no',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$')], verbose_name='Dealer Number'),
        ),
    ]
