# Generated by Django 2.1 on 2020-02-09 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_floors', models.CharField(blank=True, max_length=100, null=True, verbose_name='No. of Floors')),
                ('custom_width', models.CharField(blank=True, max_length=100, null=True, verbose_name='Width')),
                ('custom_depth', models.CharField(blank=True, max_length=100, null=True, verbose_name='Depth')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('delivery_date', models.DateField(blank=True, default=None, null=True)),
                ('ordered_on', models.DateField(auto_now_add=True)),
                ('user_image', models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='pdf-images')),
            ],
        ),
        migrations.CreateModel(
            name='ContainerPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_floors', models.CharField(max_length=100, verbose_name='No. of Floors')),
                ('variant', models.CharField(max_length=100, verbose_name='Variant')),
                ('square_feet', models.CharField(max_length=100, verbose_name='Approximate Square Feet')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Price')),
                ('price21', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Delivered Price Delivered to site for 21 or more units')),
            ],
            options={
                'verbose_name': 'Containers Pricing',
                'verbose_name_plural': 'Containers Pricing',
            },
        ),
        migrations.CreateModel(
            name='CustomContainerPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sqfeet_per_room', models.CharField(max_length=100, verbose_name='Approximate Square Feet per room')),
                ('custom_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Price per 290s.f. room(for 20units or less)')),
                ('custom_price21', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Price per 290s.f. room(for 21units or more)')),
            ],
            options={
                'verbose_name': 'Custom Containers Pricing',
                'verbose_name_plural': 'Custom  Containers Pricing',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Material Name')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialQuotations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(default=None, max_length=100, verbose_name='Material Name')),
                ('user_name', models.CharField(max_length=100, verbose_name='Name:')),
                ('company_name', models.CharField(max_length=100, verbose_name='Company Name:')),
                ('price', models.CharField(max_length=100, verbose_name='Price')),
                ('time_date', models.DateTimeField(auto_now_add=True, verbose_name='Quotation Date')),
            ],
            options={
                'verbose_name': 'MaterialQuotation',
                'verbose_name_plural': 'MaterialQuotations',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('l_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('company_name', models.CharField(blank=True, help_text='Optional', max_length=100, null=True, verbose_name='Name of Company')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Optional', max_length=18, null=True, region=None, verbose_name='Phone Number')),
                ('zipcode', localflavor.us.models.USZipCodeField(blank=True, max_length=10, null=True, verbose_name='Zip Code')),
                ('letter_of_credit', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=5, null=True, verbose_name='Do you have a Letter of Credit?')),
                ('how_much_letter_of_credit', models.CharField(blank=True, help_text='in USD$', max_length=50, null=True, verbose_name='What is the value of your Letter of Credit (in USD)?')),
                ('line_of_credit', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=5, null=True, verbose_name='Do you have a Line of Credit?')),
                ('how_much_line_of_credit', models.CharField(blank=True, help_text='in USD$', max_length=50, null=True, verbose_name='What is the currently unused amount in your Line of Credit?')),
                ('when_to_order', models.CharField(choices=[('urgent', 'Urgent(within 30 days)'), ('other', 'Other')], default=None, max_length=50, verbose_name='When are you looking to order?')),
                ('other_when_to_order', models.CharField(blank=True, choices=[('3-6 Months', '3-6 Months'), ('6-9 Months', '6-9 Months'), ('1 Year or More', '1 Year or More')], default=None, max_length=50, null=True, verbose_name='When To Order')),
                ('type_of_climate_area', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('select all', 'Select All'), ('Heavy Snow Load', 'Heavy Snow Load'), ('High Wind', 'High Wind'), ('Tornado', 'Tornado'), ('Earthquake', 'Earthquake'), ('Desert', 'Desert'), ('Other', 'Other ')], max_length=300, null=True, verbose_name='On which type of climate area(s) will the development(s) be sited? ')),
                ('other_type_of_climate_area', models.CharField(blank=True, max_length=200, null=True, verbose_name='Other')),
                ('septic_infrastructure', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=100, null=True, verbose_name='Does the development site already have septic infrastructure or service?')),
                ('installation_septic_infrastructure', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default=None, max_length=100, null=True, verbose_name='Does it require the installation of septic infrastructure? (There will be a charge for initial infrastructure installation and periodic maintenance service charges.) ')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buyer Application',
                'verbose_name_plural': 'Buyer Applications',
            },
        ),
        migrations.AddField(
            model_name='cartorder',
            name='custom_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.CustomContainerPricing'),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='order_items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.ContainerPricing'),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
