# Generated by Django 2.2.3 on 2019-08-18 18:34

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='XXX-XXX-XXXX', max_length=18, region=None, verbose_name='Phone Number'),
        ),
    ]
