# Generated by Django 2.2.3 on 2019-07-22 16:12

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='how_much_letter_of_credit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='What is the value of your Letter of Credit (in USD)?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='how_much_line_of_credit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='What is the currently unused amount in your Line of Credit?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='installation_septic_infrastructure',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default=None, max_length=100, null=True, verbose_name='Does it require the installation of septic infrastructure? (There will be a charge for initial infrastructure installation and periodic maintenance service charges.) '),
        ),
        migrations.AlterField(
            model_name='order',
            name='other_when_to_order',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(31)], verbose_name='Other (days)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_of_climate_area',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Heavy Snow Load', 'Heavy Snow Load'), ('High Wind', 'High Wind'), ('Tornado', 'Tornado'), ('Earthquake', 'Earthquake'), ('Desert', 'Desert'), ('Other', 'Other ')], max_length=300, null=True, verbose_name='On which type of climate area(s) will the development(s) be sited? '),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_of_electric_vehicle_function',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Standard', 'Standard'), ('Capability to Load Handicapped Person Without Human Assistance', 'Capability to Load Handicapped Person Without Human Assistance')], max_length=300, null=True, verbose_name='An electric vehicle will be included with each housing unit. What type of electric vehicle function are you interested in?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='when_to_order',
            field=models.CharField(choices=[('urgent', 'Urgent(within 30 days)'), ('other', 'Other (days)')], default=None, max_length=50, verbose_name='When are you looking to order?'),
        ),
    ]
