# Generated by Django 2.2.3 on 2020-02-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Optional', max_length=18, null=True, verbose_name='Phone Number'),
        ),
    ]
