# Generated by Django 2.2.3 on 2020-01-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='company_name',
            field=models.CharField(blank=True, help_text='Optional', max_length=100, null=True, verbose_name='Name of Company'),
        ),
    ]
