# Generated by Django 2.2.3 on 2019-07-25 18:44

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190722_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type_of_climate_area',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('select all', 'Select All'), ('Heavy Snow Load', 'Heavy Snow Load'), ('High Wind', 'High Wind'), ('Tornado', 'Tornado'), ('Earthquake', 'Earthquake'), ('Desert', 'Desert'), ('Other', 'Other ')], max_length=300, null=True, verbose_name='On which type of climate area(s) will the development(s) be sited? '),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_of_development',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('select all', 'Select All'), ('Commercial', 'Commercial'), ('Mixed-use', 'Mixed-use'), ('Multi-tenant', 'Multi-tenant'), ('Condominium', 'Condominium'), ('Townhome', 'Townhome'), ('Man Camp', 'Man Camp'), ('Mobile Home Park', 'Mobile Home Park'), ('RV Park', 'RV Park'), ('Park Home (as defined by Housing and Urban Development)', 'Park Home (as defined by Housing and Urban Development)'), ('Other', 'Other')], max_length=300, null=True, verbose_name='What type of development(s) are you seeking?'),
        ),
    ]
