# Generated by Django 2.2.3 on 2020-06-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200220_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerpricing',
            name='model_image',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Model Image'),
        ),
    ]
