# Generated by Django 2.1 on 2019-10-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialQuotations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='Name:')),
                ('company_name', models.CharField(max_length=100, verbose_name='Company Name:')),
                ('price', models.CharField(max_length=100, verbose_name='Price')),
                ('time_date', models.DateTimeField(auto_now_add=True, verbose_name='Quotation Date')),
            ],
        ),
    ]
