# Generated by Django 2.1 on 2020-01-31 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200125_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='learn_about_electric_drive',
        ),
        migrations.RemoveField(
            model_name='order',
            name='other_type_of_development',
        ),
        migrations.RemoveField(
            model_name='order',
            name='type_of_development',
        ),
        migrations.RemoveField(
            model_name='order',
            name='type_of_electric_vehicle_function',
        ),
        migrations.RemoveField(
            model_name='order',
            name='type_of_smart_home',
        ),
    ]
