# Generated by Django 2.1 on 2019-12-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_containerpricing_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containerpricing',
            name='delivery_date',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='delivery_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
