# Generated by Django 2.2.3 on 2020-06-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_containerpricing_model_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerpricing',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Model Name'),
        ),
    ]
