# Generated by Django 2.2.3 on 2019-07-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190725_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='how_much_letter_of_credit',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='What is the value of your Letter of Credit (in USD)?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='how_much_line_of_credit',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='What is the currently unused amount in your Line of Credit?'),
        ),
    ]
