# Generated by Django 2.1 on 2019-10-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_materialquotations'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialquotations',
            name='material_name',
            field=models.CharField(default=None, max_length=100, verbose_name='Material Name'),
        ),
    ]
