# Generated by Django 2.1 on 2019-12-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20191213_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerpricing',
            name='price21',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Price'),
        ),
    ]
