# Generated by Django 2.1 on 2019-11-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_materialquotations_material_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialquotations',
            options={'verbose_name': 'MaterialQuotation', 'verbose_name_plural': 'MaterialQuotations'},
        ),
        migrations.AlterField(
            model_name='order',
            name='other_when_to_order',
            field=models.CharField(choices=[('3-6 Months', '3-6 Months'), ('6-9 Months', '6-9 Months'), ('1 Year or More', '1 Year or More')], default=None, max_length=50, verbose_name='When To Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='when_to_order',
            field=models.CharField(choices=[('urgent', 'Urgent(within 30 days)'), ('other', 'Other')], default=None, max_length=50, verbose_name='When are you looking to order?'),
        ),
    ]
