# Generated by Django 2.1 on 2019-12-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_containerpricing_price21'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerpricing',
            name='price21',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Delivered Price Delivered to site for 21 or more units'),
        ),
    ]
