# Generated by Django 2.1 on 2019-11-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20191116_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='other_when_to_order',
            field=models.CharField(blank=True, choices=[('3-6 Months', '3-6 Months'), ('6-9 Months', '6-9 Months'), ('1 Year or More', '1 Year or More')], default=None, max_length=50, null=True, verbose_name='When To Order'),
        ),
    ]
