# Generated by Django 2.1 on 2019-12-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20191116_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_floors', models.CharField(default=None, max_length=100, verbose_name='No. of Floors')),
                ('variant', models.CharField(max_length=100, verbose_name='Variant')),
                ('square_feet', models.CharField(max_length=100, verbose_name='Approximate Square Feet')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Containers Pricing',
                'verbose_name_plural': 'Containers Pricing',
            },
        ),
    ]
