# Generated by Django 2.2.3 on 2020-06-30 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20200630_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='buyer_app_obj',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='delivery_info_obj',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.DeliveryInfo'),
        ),
    ]
