# Generated by Django 2.1 on 2019-12-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20191218_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomContainerPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sqfeet_per_room', models.CharField(max_length=100, verbose_name='Approximate Square Feet per room')),
                ('custom_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Price per 290s.f. room(for 20units or less)')),
                ('custom_price21', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Price per 290s.f. room(for 21units or more)')),
            ],
            options={
                'verbose_name': 'Custom Containers Pricing',
                'verbose_name_plural': 'Custom  Containers Pricing',
            },
        ),
    ]
