# Generated by Django 2.1 on 2019-12-08 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191030_2202'),
        ('order', '0007_containerpricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerpricing',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.SpecUser'),
        ),
    ]
