# Generated by Django 2.1 on 2019-12-22 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_cartorder_custom_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='order_items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.ContainerPricing'),
        ),
    ]
