# Generated by Django 2.1 on 2019-12-08 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191030_2202'),
        ('order', '0008_containerpricing_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SpecUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='containerpricing',
            name='user',
        ),
    ]
