# Generated by Django 2.1 on 2019-12-08 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20191208_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='order_items',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='order.ContainerPricing'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.SpecUser'),
        ),
    ]
