# Generated by Django 2.1 on 2019-12-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20191222_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='custom_depth',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Depth'),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='custom_floors',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='No. of Floors'),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='custom_width',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Width'),
        ),
    ]
