# Generated by Django 2.1 on 2019-12-08 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20191208_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='quantity',
            field=models.PositiveIntegerField(default=None, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
