# Generated by Django 2.1 on 2019-12-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_cartorder_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='user_image',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='pdf-images'),
        ),
    ]
