# Generated by Django 2.1 on 2019-12-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20191208_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='ordered_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
