# Generated by Django 2.1 on 2019-12-08 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_cartorder_ordered_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='order_items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.ContainerPricing'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='ordered_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='containerpricing',
            name='no_of_floors',
            field=models.CharField(max_length=100, verbose_name='No. of Floors'),
        ),
    ]
